apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: faker-mcp
  labels:
    app.kubernetes.io/name: faker-mcp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /faker-mcp
spec:
  ingressClassName: nginx
  rules:
    - host: free.cadenya.com
      http:
        paths:
          - path: /faker-mcp
            pathType: Prefix
            backend:
              service:
                name: faker-mcp
                port:
                  number: 8080
  tls:
    - hosts:
        - free.cadenya.com
      secretName: free-cadenya-com-tls
